# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-16 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='need',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('need_id', models.IntegerField(null=True)),
                ('need_name', models.CharField(max_length=100)),
                ('need_status', models.CharField(max_length=20)),
                ('finish_test', models.CharField(max_length=10)),
                ('need_tester', models.CharField(max_length=20)),
                ('need_day', models.CharField(max_length=15)),
                ('need_url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('duty', models.CharField(max_length=50)),
            ],
        ),
    ]
